name: Workflow Commands
on: [push]

jobs:
  generate-a-secret-output:
    runs-on: ubuntu-latest

  steps:
  - name: Set the value
    id: step_one
    run: |
      echo "action_state=yellow" >> "$GITHUB_ENV"
  - name: Use the value
    id: step_two
    run: |
      printf '%s\n' "$action_state" # This will output 'yellow'
